version: '3.8'

services:
  
  api:
    container_name: sdc-chat-webapp
    image: sdc-chat-webapp:latest
    restart: on-failure
    build:
      context: ../.
      dockerfile: ./src/SDC.Chat.WebApp/Dockerfile
    ports:
        - 5010:8080
    networks:
        - sdc-chat-net
    environment:
        - ASPNETCORE_ENVIRONMENT=Local
    depends_on:
      - sqlserver

  sqlserver:
    container_name: sdc-chat-sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: localhost
    ports:
        - 1433:1433
    networks:
        - sdc-chat-net
    environment:
        - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
        - MSSQL_PID=${MSSQL_PID}
        - ACCEPT_EULA=Y

networks:
  sdc-chat-net:
    driver: bridge
